### ISSUE TITLE
Link generation error

### ISSUE THREAD

**Issue by axtamari** [htr-tech/zphisher#126]
1. [!]  Ngrok was unable to Generate Link.. Try Again..[!]

, 
2. Termux not generate renew link . Gives me the same link again, does not change the link for a new start

**Comment by htr-tech** [comment]
@axtamari if you are root then try with sudo..

turn on hotspot & use option 2 ... if you want hotspot free version then use option 3
```
killall php > /dev/null 2>&1
killall ngrok > /dev/null 2>&1
```
use these 2 commands if same link appears multiple time ...

**Comment by htr-tech** [comment]
fixed !

**Comment by kizzajamie** [comment]
I still can't generate a link on Termux it only gives u URL 2

**Comment by sadeeq-bite** [comment]
i need help pls ngrok does not a link, it only gives url2

**Comment by sadeeq-bite** [comment]
x-special/nautilus-clipboard
copy
file:///home/user/Pictures/Screenshot%20from%202021-05-13%2021-59-13.png

**Comment by htr-tech** [comment]
> I still can't generate a link on Termux it only gives u URL 2

remove the zphisher directory & clone again ..

**Comment by htr-tech** [comment]
> i need help pls ngrok does not generate a link, it only gives url2

remove the zphisher directory & clone again ..

**Comment by sadeeq-bite** [comment]
it still did not solve the problem " ./zphisher.sh: line 352: curl: command not fou"

**Comment by hackpekka** [comment]
> > i need help pls ngrok does not generate a link, it only gives url2
> 
> remove the zphisher directory & clone again ..

But how? It showing just url 2
