### ISSUE TITLE
No Link

### ISSUE THREAD

**Issue by kzubec** [htr-tech/zphisher#186]
Hello👋 I go to vk > traditional login > without hotspot, and there is no link
![Screenshot_2021-02-21-14-57-33-396_com termux](https://user-images.githubusercontent.com/77785957/108623056-db91c780-744d-11eb-9293-7764b446bbfc.jpg)

**Comment by Jerukpurut** [comment]
Had the same problem too

**Comment by SalehLardhi** [comment]
We need someone to solve this problem, i can't get the link, idk why?

**Comment by htr-tech** [comment]
@Jerukpurut @SalehLardhi I have fixed these problems in latest update,,

try re-cloning the tool .. this time no hotspot is required !!!

- `rm -rf ~/zphisher`
- `git clone https://github.com/htr-tech/zphisher.git`
- `cd zphisher`
- `bash zphisher.sh`

use option 2 Ngrok 💯 if this works then plz let me know 😄

**Comment by J35t3rOP** [comment]
Hello, @htr-tech. I still have the same error and i don't understand why. I've done all tutorials from all over the internet and nothing works. I have a Huawei P20 Pro and i run termux. The ngrok link doesent work. I appears nothing.

**Comment by htr-tech** [comment]
> Hello, @htr-tech. I still have the same error and i don't understand why. I've done all tutorials from all over the internet and nothing works. I have a Huawei P20 Pro and i run termux. The ngrok link doesent work. I appears nothing.

- `apt isntall proot resolv-conf -y`
- `cd zphisher`
- `termux-chroot bash zphisher.sh`

try this 😖

**Comment by J35t3rOP** [comment]
@htr-tech still doesent work that way but i found a fix that works well. I downloaded ngrok for linux, added my authtoken and after that i made it executable with "chmod +x ngrok". I ran zphisher with the localhost option and run ngrok in another termux tab with "./ngrok http 8080". Works like a charm. Now i'm trying to delete the version of ngrok that zphisher has and try to add this one. I'll keep you posted if i manage something.

**Comment by htr-tech** [comment]
> @htr-tech still doesent work that way but i found a fix that works well. I downloaded ngrok for linux, added my authtoken and after that i made it executable with "chmod +x ngrok". I ran zphisher with the localhost option and run ngrok in another termux tab with "./ngrok http 8080". Works like a charm. Now i'm trying to delete the version of ngrok that zphisher has and try to add this one. I'll keep you posted if i manage something.

in the zphisher directory go to `.server` directory & replace the ngrok

**Comment by J35t3rOP** [comment]
@htr-tech it worked! Now i can use ngrok in zphisher, but only with hotspot. If you dont activate hotspot ngrok doesent connect to their servers.

**Comment by J35t3rOP** [comment]
![Screenshot_20210305_094115](https://user-images.githubusercontent.com/60807708/110083232-1fae9180-7d97-11eb-95f9-1a2937f36684.jpg)

I would change the url 2 options and integrate JayKali's MaskPhish, iti does a much better job at masking the link.
